---
# Sandbox-specific Ansible connection overrides.
# Disables strict host key checking since VM host keys change after each
# "terraform destroy / apply" cycle.
ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
